/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeusAgendamentosRouteImport } from './routes/meus-agendamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksResetMonthlyAppointmentsRouteImport } from './routes/hooks/reset-monthly-appointments'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusAgendamentosRoute = MeusAgendamentosRouteImport.update({
  id: '/meus-agendamentos',
  path: '/meus-agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksResetMonthlyAppointmentsRoute =
  HooksResetMonthlyAppointmentsRouteImport.update({
    id: '/hooks/reset-monthly-appointments',
    path: '/hooks/reset-monthly-appointments',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/convite': typeof ConviteRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/onboarding': typeof OnboardingRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/upgrade': typeof UpgradeRoute
  '/hooks/reset-monthly-appointments': typeof HooksResetMonthlyAppointmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/convite': typeof ConviteRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/onboarding': typeof OnboardingRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/upgrade': typeof UpgradeRoute
  '/hooks/reset-monthly-appointments': typeof HooksResetMonthlyAppointmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/convite': typeof ConviteRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/onboarding': typeof OnboardingRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/upgrade': typeof UpgradeRoute
  '/hooks/reset-monthly-appointments': typeof HooksResetMonthlyAppointmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/configuracoes'
    | '/convite'
    | '/dashboard'
    | '/login'
    | '/meus-agendamentos'
    | '/onboarding'
    | '/relatorios'
    | '/servicos'
    | '/upgrade'
    | '/hooks/reset-monthly-appointments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/configuracoes'
    | '/convite'
    | '/dashboard'
    | '/login'
    | '/meus-agendamentos'
    | '/onboarding'
    | '/relatorios'
    | '/servicos'
    | '/upgrade'
    | '/hooks/reset-monthly-appointments'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/agendar'
    | '/configuracoes'
    | '/convite'
    | '/dashboard'
    | '/login'
    | '/meus-agendamentos'
    | '/onboarding'
    | '/relatorios'
    | '/servicos'
    | '/upgrade'
    | '/hooks/reset-monthly-appointments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AgendarRoute: typeof AgendarRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConviteRoute: typeof ConviteRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MeusAgendamentosRoute: typeof MeusAgendamentosRoute
  OnboardingRoute: typeof OnboardingRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ServicosRoute: typeof ServicosRoute
  UpgradeRoute: typeof UpgradeRoute
  HooksResetMonthlyAppointmentsRoute: typeof HooksResetMonthlyAppointmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-agendamentos': {
      id: '/meus-agendamentos'
      path: '/meus-agendamentos'
      fullPath: '/meus-agendamentos'
      preLoaderRoute: typeof MeusAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/reset-monthly-appointments': {
      id: '/hooks/reset-monthly-appointments'
      path: '/hooks/reset-monthly-appointments'
      fullPath: '/hooks/reset-monthly-appointments'
      preLoaderRoute: typeof HooksResetMonthlyAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AgendarRoute: AgendarRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConviteRoute: ConviteRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MeusAgendamentosRoute: MeusAgendamentosRoute,
  OnboardingRoute: OnboardingRoute,
  RelatoriosRoute: RelatoriosRoute,
  ServicosRoute: ServicosRoute,
  UpgradeRoute: UpgradeRoute,
  HooksResetMonthlyAppointmentsRoute: HooksResetMonthlyAppointmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
