// This file is automatically generated. Do not edit it directly.
//
// EXCEÇÃO MANUAL: o bloco marcado com "modo mock" abaixo é a única alteração
// local. Se este arquivo for regerado, reaplique-a. Ver src/lib/data-source.ts.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isMockDataSource } from '@/lib/data-source';
import { mockSupabaseClient } from '@/mocks/client';

type SupabaseClientInstance = ReturnType<typeof createRealSupabaseClient>;

function createSupabaseClient(): SupabaseClientInstance {
  // --- modo mock: nenhuma variável de ambiente é lida e nenhuma conexão é aberta ---
  if (isMockDataSource) {
    console.info('[data-source] VITE_DATA_SOURCE=mock — usando dados fictícios locais.');
    // Cast único e centralizado: o mock implementa apenas o subconjunto da API
    // do supabase-js que este app utiliza.
    return mockSupabaseClient as unknown as SupabaseClientInstance;
  }

  return createRealSupabaseClient();
}

function createRealSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      'Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.'
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

